#CXX=x86_64-w64-mingw32-g++
CXX=/usr/local/Cellar/mingw-w64/6.0.0_1/toolchain-x86_64/bin/x86_64-w64-mingw32-g++
CXXFLAGS=-Wall -O3 -std=gnu++11 -DNDEBUG -static -lpthread -lpsapi
INCLUDES := -I inc/ -isystem lib/ -isystem window/zlib-1.2.11/
CPPSRC := src/*.cpp
OBJ := bgen_lib.o binaryplink.o genotype.o misc.o regression.o snp.o binarygen.o commander.o main.o plink_common.o prsice.o region.o reporter.o gzstream.o dcdflib.o
ZLIB := window/zlib-1.2.11/libz.a /usr/local/Cellar/mingw-w64/6.0.0_1/toolchain-x86_64/x86_64-w64-mingw32/lib/libpsapi.a 
%.o: src/%.cpp
		$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

PRSice_win64.exe: $(OBJ)
		$(CXX) $(CXXFLAGS) $(INCLUDES)  $^ $(ZLIB) -o $@
